SELECT USER
FROM DUAL;
--==>> PROJECTORS

/*
-- 샘플
CREATE TABLE USER_TOOL
( USER_TOOL_NO NUMBER(★) 
, USER_PIN_NO VARCHAR2(★)
, TOOL_NO NUMBER(★)
, CONSTRAINT USER_TOOL_NO_PK PRIMARY KEY(USER_TOOL_NO)
, CONSTRAINT USER_PIN_NO_FK FOREIGN KEY(USER_PIN_NO)
		           REFERENCES USER_PIN(USER_PIN_NO)
, CONSTRAINT TOOL_NO_FK FOREIGN KEY(TOOL_NO)
		 	   REFERENCES TOOL(TOOL_NO)
);
--============================================================
--============================================================
*/

--[1] 회원식별 번호
CREATE TABLE USER_PIN
( PIN_NO      VARCHAR2(16)
, JOIN_DATE   DATE           DEFAULT SYSDATE
, CONSTRAINT PIN_NO_PK PRIMARY KEY(PIN_NO)
);
--==>>Table USER_PIN이(가) 생성되었습니다.

--[2] 포지션
CREATE TABLE POSITION
( POS_NO   NUMBER(2)
, POS_NAME VARCHAR2(40) NOT NULL
, CONSTRAINT POS_NO_PK PRIMARY KEY(POS_NO)
);
--==>>Table POSITION이(가) 생성되었습니다.

--[3] 지역
CREATE TABLE REGION
( REGION_NO     NUMBER(3)
, REGION_NAME   VARCHAR2(40) NOT NULL
, CONSTRAINT REGION_NO_PK PRIMARY KEY(REGION_NO)
);
--==>> Table REGION이(가) 생성되었습니다.



--[4] 도구
CREATE TABLE TOOL
( TOOL_NO       NUMBER(3)
, TOOL_NAME     VARCHAR2(40)    NOT NULL
, CONSTRAINT TOOL_NO_PK PRIMARY KEY(TOOL_NO)
);
--==>> Table TOOL이(가) 생성되었습니다.

--[5] 관리자
CREATE TABLE ADMIN
( ADMIN_NO VARCHAR2(16)
, ADMIN_ID VARCHAR2(100)    NOT NULL
, ADMIN_PW VARCHAR2(20)     NOT NULL
, REG_DATE DATE         DEFAULT SYSDATE
, CONSTRAINT ADMIN_NO_PK PRIMARY KEY(ADMIN_NO)
);
--==>> Table ADMIN이(가) 생성되었습니다.

ALTER TABLE ADMIN
ADD CONSTRAINT ADMIN_ID_UK UNIQUE(ADMIN_ID);
--==>> Table ADMIN이(가) 변경되었습니다.


--[6] FAQ 자주 묻는 질문
CREATE TABLE FAQ
( FAQ_NO    NUMBER(3)
, TITLE     VARCHAR2(100)   NOT NULL
, CONTENT   VARCHAR2(1000)  NOT NULL
, CONSTRAINT FAQ_NO_PK PRIMARY KEY(FAQ_NO)
);
--==>>  Table FAQ이(가) 생성되었습니다.


--[7] 신고 사유
CREATE TABLE REPORT_REASON
( REP_REASON_NO     NUMBER(2)
, REASON            VARCHAR2(50)  NOT NULL
, CONSTRAINT REP_REASON_NO_PK PRIMARY KEY(REP_REASON_NO)
);
--==>> Table REPORT_REASON이(가) 생성되었습니다.


--[8] 신고 처리 결과
CREATE TABLE REPORT_RESULT
( REP_RESULT_NO     NUMBER(1)
, RESULT            VARCHAR2(20)   NOT NULL
, CONSTRAINT REP_RESULT_NO_PK PRIMARY KEY(REP_RESULT_NO)
, CONSTRAINT REP_RESULT_NO_CK CHECK (REP_RESULT_NO = 1 OR REP_RESULT_NO = 0)
);
--==>> Table REPORT_RESULT이(가) 생성되었습니다.

ALTER TABLE REPORT_RESULT MODIFY REP_RESULT_NO NUMBER(2);
--==>> Table REPORT_RESULT이(가) 변경되었습니다.


--[9] 제재 내용
CREATE TABLE REGULATION
( REGU_NO   NUMBER(1)
, CONTENT   VARCHAR2(50) NOT NULL
, CONSTRAINT REGU_NO_PK PRIMARY KEY(REGU_NO)
);
--==>> Table REGULATION이(가) 생성되었습니다.

--[10] 제재 기간
CREATE TABLE REGULATION_PERIOD
( REGU_PERIOD_NO    NUMBER(1)
, PERIOD            NUMBER(5)   NOT NULL
, CONSTRAINT REGU_PERIOD_NO_PK PRIMARY KEY(REGU_PERIOD_NO)
);
--==>> Table REGULATION_PERIOD이(가) 생성되었습니다.

--[11] 프로젝트 중단 사유
CREATE TABLE PRJ_STOP_REASON
( STOP_REASON_NO    NUMBER(1)
, REASON            VARCHAR2(50) NOT NULL
, CONSTRAINT STOP_REASON_NO_PK PRIMARY KEY(STOP_REASON_NO)
);
--==>> Table PRJ_STOP_REASON이(가) 생성되었습니다.

--[12] (프로젝트) 개인 이탈 사유
CREATE TABLE MEM_OUT_REASON
( OUT_REASON_NO     NUMBER(1)
, REASON            VARCHAR2(50)  NOT NULL
, CONSTRAINT OUT_REASON_NO_PK PRIMARY KEY(OUT_REASON_NO)
);
--==>> Table MEM_OUT_REASON이(가) 생성되었습니다.


-- 평가들 보다 먼저 만들어져야함
-- [13] RATE_SELECT 평가 선택지
-- 평가선택지번호, 평가내용
CREATE TABLE RATE_SELECT
( RATE_NO       NUMBER(1)   -- 선택지 6개
, CONTENT       VARCHAR2(30)    NOT NULL
, CONSTRAINT RATE_NO_PK PRIMARY KEY(RATE_NO)
);
--==>> Table RATE_SELECT이(가) 생성되었습니다.

ALTER TABLE RATE_SELECT
ADD CONSTRAINT RATE_NO_CK CHECK(RATE_NO BETWEEN 1 AND 6);
--==>> Table RATE_SELECT이(가) 변경되었습니다.


-- 프로젝트 공고보다 먼저 만들어져야하는 테이블
-- [14] DO_TYPE 대면여부
-- 진행방식번호, 진행방식명
-- DO_TYPE_NAME (NN)
CREATE TABLE DO_TYPE
( DO_TYPE_NO    NUMBER(1)   -- 대면 / 비대면
, DO_TYPE_NAME  VARCHAR2(10)     NOT NULL
, CONSTRAINT DO_TYPE_NO_PK PRIMARY KEY(DO_TYPE_NO)
, CONSTRAINT DO_TYPE_NO_CK CHECK (DO_TYPE_NO=0 OR DO_TYPE_NO=1)
);
--==>> Table DO_TYPE이(가) 생성되었습니다.

-- 프로젝트 신고 이전에 언제든 만들어도 상관없음
-- [15] REP_PRJ_RREASON 프로젝트 신고사유
-- 프로젝트신고사유현황, 프로젝트 신고사유내용
-- REP_REASON (NN)
CREATE TABLE REP_PRJ_REASON
( REP_REASON_NO     NUMBER(2)
, REP_REASON        VARCHAR2(50)  NOT NULL
, CONSTRAINT PRJ_REP_REASON_NO_PK PRIMARY KEY(REP_REASON_NO)
);
--==>> Table REP_PRJ_REASON이(가) 생성되었습니다.


--[16] 회원
CREATE TABLE USERS
( USER_NO   VARCHAR2(16)
, PIN_NO    VARCHAR2(16)    -- 탈퇴시 FK 관계 끊어야하므로
, ID        VARCHAR2(100)       NOT NULL
, PW        VARCHAR2(20)        NOT NULL
, NICKNAME  VARCHAR2(20)        NOT NULL
, PHOTOURL  VARCHAR2(400)       NOT NULL
, CONSTRAINT USER_NO_PK PRIMARY KEY(USER_NO)
, CONSTRAINT ID_UK UNIQUE(ID)
, CONSTRAINT NICKNAME_UK UNIQUE(NICKNAME)
, CONSTRAINT PIN_NO FOREIGN KEY (PIN_NO)
            REFERENCES USER_PIN(PIN_NO)
);
--==>>Table USERS이(가) 생성되었습니다.
/*
※ USER -> USERS로 바꿨음 아래 참조키에서 테이블명 다 바꿔주어야 함 23.08.01 22:00 현재 아직 바꿀 거 없음
*/


--== ㅁ


--[17] 세부 지역
CREATE TABLE SUB_REGION
( SUB_REGION_NO     NUMBER(3)
, REGION_NO         NUMBER(3)       NOT NULL
, SUB_REGION_NAME   VARCHAR2(40)    NOT NULL
, CONSTRAINT SUB_REGION_NO_PK PRIMARY KEY(SUB_REGION_NO)
, CONSTRAINT REGION_NO_FK FOREIGN KEY(REGION_NO)
                        REFERENCES REGION(REGION_NO)
);
--==>> Table SUB_REGION이(가) 생성되었습니다.

--[18] 유저 사용도구
CREATE TABLE USER_TOOL
( UTOOL_NO  VARCHAR2(16)
, PIN_NO    VARCHAR2(16)        NOT NULL
, TOOL_NO   NUMBER(3)           NOT NULL
, CONSTRAINT UTOOL_NO_PK PRIMARY KEY(UTOOL_NO)
, CONSTRAINT PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT TOOL_NO_FK FOREIGN KEY(TOOL_NO)
                        REFERENCES TOOL(TOOL_NO)
);
--==>> Table USER_TOOL이(가) 생성되었습니다.

--[19] 탈퇴 방법 사유
CREATE TABLE WITHDRAW_TYPE
( WD_TYPE_NO        NUMBER(1)
, WD_TYPE_CONTENT   VARCHAR2(50) NOT NULL
, CONSTRAINT WD_TYPE_NO_PK PRIMARY KEY(WD_TYPE_NO)
);
--==>> Table WITHDRAW_TYPE이(가) 생성되었습니다.



--[20] 공지 게시판(관리자)
CREATE TABLE ADMIN_NOTICE
( ADMIN_NOTICE_NO   VARCHAR2(8)
, ADMIN_NO          VARCHAR2(16) NOT NULL
, TITLE             VARCHAR2(100) NOT NULL
, CONTENT           VARCHAR2(1000) NOT NULL
, CONSTRAINT ADMIN_NOTICE_NO_PK PRIMARY KEY(ADMIN_NOTICE_NO)
, CONSTRAINT ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                        REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table ADMIN_NOTICE이(가) 생성되었습니다.


--[21] 비활성 관리자
CREATE TABLE QUIT_ADMIN
( QUIT_ADMIN_NO   NUMBER(4)
, ADMIN_NO        VARCHAR2(16)   NOT NULL
, QUIT_DATE       DATE           DEFAULT SYSDATE
, CONSTRAINT QUIT_ADMIN_NO_PK PRIMARY KEY(QUIT_ADMIN_NO)
, CONSTRAINT QUIT_ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                        REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table QUIT_ADMIN이(가) 생성되었습니다.

--[22] 1:1문의글 중 질문
CREATE TABLE QUESTION
( QUESTION_NO   VARCHAR2(12)
, PIN_NO        VARCHAR2(16)     NOT NULL
, TITLE         VARCHAR2(100)     NOT NULL
, CONTENT       VARCHAR2(1000)     NOT NULL
, CREATED_DATE  DATE            DEFAULT SYSDATE
, CONSTRAINT QUESTION_NO_PK PRIMARY KEY(QUESTION_NO)
, CONSTRAINT QUESTION_PIN_NO_FK  FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
);
--==>> Table QUESTION이(가) 생성되었습니다.


--[23] 유저 로그인 로그
CREATE TABLE LOGIN_REC
( LOGIN_REC  NUMBER
, PIN_NO     VARCHAR2(16) NOT NULL
, LOGIN_DATE DATE   DEFAULT SYSDATE
, CONSTRAINT LOGIN_REC_PK PRIMARY KEY(LOGIN_REC)
, CONSTRAINT LOGIN_PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
);
--==>> Table LOGIN_REC이(가) 생성되었습니다.


--[24] 유저 로그아웃 로그
CREATE TABLE LOGOUT_REC
( LOGOUT_REC NUMBER
, PIN_NO     VARCHAR2(16) NOT NULL
, LOGIN_DATE DATE        DEFAULT SYSDATE
, CONSTRAINT LOGOUT_REC_PK PRIMARY KEY(LOGOUT_REC)
, CONSTRAINT LOGOUT_PIN_NO_FK FOREIGN KEY(PIN_NO)
                       REFERENCES USER_PIN(PIN_NO)
);
--==>> Table LOGOUT_REC이(가) 생성되었습니다.

--[25] 모집 공고
CREATE TABLE RECRUIT
( RECRUIT_NO    VARCHAR2(16)
, PIN_NO        VARCHAR2(16)    NOT NULL
, DO_TYPE_NO    NUMBER(1)       NOT NULL
, TITLE         VARCHAR2(100)   NOT NULL
, CONTENT       VARCHAR2(3000)  NOT NULL 
, CREATED_DATE  DATE          DEFAULT SYSDATE
, PRJ_START     DATE          NOT NULL
, PRJ_END       DATE          NOT NULL
, CONSTRAINT RECRUIT_NO_PK PRIMARY KEY(RECRUIT_NO)
, CONSTRAINT RECRUIT_PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT RECRUIT_DO_TYPE_NO_FK FOREIGN KEY(DO_TYPE_NO)
                            REFERENCES DO_TYPE(DO_TYPE_NO)
);
--==>> Table RECRUIT이(가) 생성되었습니다.


-- 식별번호 뒤에만 만들어지면 됨
-- [26] NOTE 쪽지
-- 쪽지번호, 보낸사람, 받은사람, 보낸날짜, 읽은날짜, 제목, 내용, 보낸사람삭제일, 받는사람삭제일
-- 보낸사람, 받은사람 (FK, NN) (PIN_NO)
-- 보낸날짜 DEFAULT SYSDATE
CREATE TABLE NOTE
( NOTE_NO       VARCHAR2(16)
, SENDER        VARCHAR2(16)    NOT NULL
, READER        VARCHAR2(16)    NOT NULL
, SEND_DATE     DATE    DEFAULT SYSDATE
, READ_DATE     DATE
, TITLE         VARCHAR2(100)   NOT NULL
, CONTENT       VARCHAR2(1000)  NOT NULL
, SEND_DEL      DATE
, READ_DEL      DATE
, CONSTRAINT NOTE_NO_PK PRIMARY KEY(NOTE_NO)
, CONSTRAINT NOTE_SENDER_FK FOREIGN KEY (SENDER)
            REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT NOTE_READER_FK FOREIGN KEY (READER)
            REFERENCES USER_PIN(PIN_NO)
);
--==>> Table NOTE이(가) 생성되었습니다.


--[27] 탈퇴 회원
CREATE TABLE WITHDRAW_USER
( WD_USER_NO    NUMBER(8)
, PIN_NO        VARCHAR2(16)     NOT NULL
, WD_DATE       DATE             DEFAULT SYSDATE
, ID            VARCHAR2(100)     NOT NULL
, WD_TYPE_NO    NUMBER(1)       NOT NULL
, CONSTRAINT WD_USER_NO_PK PRIMARY KEY(WD_USER_NO)
, CONSTRAINT WD_PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT WD_TYPE_NO_FK FOREIGN KEY(WD_TYPE_NO)
                        REFERENCES WITHDRAW_TYPE(WD_TYPE_NO)
);
--==>> Table WITHDRAW_USER이(가) 생성되었습니다.

--[28] 프로필
CREATE TABLE PROFILE
( PROFILE_NO    VARCHAR2(16)
, PIN_NO        VARCHAR2(16)   NOT NULL
, POS_NO        NUMBER(2)      NOT NULL
, SUB_REGION_NO  NUMBER(3)     NOT NULL
, UTOOL_NO      VARCHAR2(16)   
, PROFILE_DATE  DATE    DEFAULT SYSDATE
, CONSTRAINT PROFILE_NO_PK PRIMARY KEY(PROFILE_NO)
, CONSTRAINT PROFILE_PIN_NO_FK  FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT PROFILE_POS_NO_FK FOREIGN KEY(POS_NO)
                        REFERENCES POSITION(POS_NO)
, CONSTRAINT SUB_REGION_NO_FK FOREIGN KEY(SUB_REGION_NO)
                        REFERENCES SUB_REGION(SUB_REGION_NO)
, CONSTRAINT UTOOL_NO_FK FOREIGN KEY(UTOOL_NO)
                        REFERENCES USER_TOOL(UTOOL_NO)
);
--===>> Table PROFILE이(가) 생성되었습니다.


--[29] 1:1문의글 중 답변
CREATE TABLE ANSWER
( ANSWER_NO     VARCHAR2(12)
, CONTENT       VARCHAR2(1000) NOT NULL
, QUESTION_NO   VARCHAR2(12) NOT NULL
, ADMIN_NO      VARCHAR2(16) NOT NULL
, CREATED_DATE  DATE         DEFAULT SYSDATE
, CONSTRAINT ANSWER_NO_PK PRIMARY KEY(ANSWER_NO)
, CONSTRAINT QUESTION_NO_FK FOREIGN KEY(QUESTION_NO)
                        REFERENCES QUESTION(QUESTION_NO)
, CONSTRAINT ANSWER_ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                        REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table ANSWER이(가) 생성되었습니다.


--[30] 댓글                   ※ 테이블명 변경 COMMENT → COMMENTS
CREATE TABLE COMMENTS
( COMM_NO       NUMBER(10)
, RECRUIT_NO    VARCHAR2(16) NOT NULL
, PIN_NO        VARCHAR2(16) NOT NULL
, CREATED_DATE  DATE        DEFAULT SYSDATE
, CONTENT       VARCHAR2(400) NOT NULL
, RECOMM_NO     NUMBER(10)
, CONSTRAINT COMM_NO_PK PRIMARY KEY(COMM_NO)
, CONSTRAINT COMM_RECRUIT_NO_FK FOREIGN KEY(RECRUIT_NO)
                            REFERENCES RECRUIT(RECRUIT_NO)
, CONSTRAINT COMM_PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT RECOMM_NO_FK FOREIGN KEY(RECOMM_NO)
                        REFERENCES COMMENTS(COMM_NO)
);
--==>>Table COMMENTS이(가) 생성되었습니다.


--[31] 모집 포지션
CREATE TABLE RECRUIT_POS
( RECRUIT_POS_NO    VARCHAR2(20)
, RECRUIT_NO        VARCHAR2(16) NOT NULL
, POS_NO            NUMBER(2)   NOT NULL
, CONSTRAINT RECRUIT_POS_NO_PK PRIMARY KEY(RECRUIT_POS_NO)
, CONSTRAINT RECRUIT_NO_FK FOREIGN KEY(RECRUIT_NO)
                            REFERENCES RECRUIT(RECRUIT_NO)
, CONSTRAINT RECRUIT_POS_NO_FK FOREIGN KEY(POS_NO)
                        REFERENCES POSITION(POS_NO)
);
--==>> Table RECRUIT_POS이(가) 생성되었습니다.

-- 공고 이후
-- [32] DEL_RECRUIT 자진비활성화공고
-- 공고비활성화번호, 공고번호, 삭제일
-- RECRUIT_NO   (FK, NN)
-- DEL_DATE     DEFAULT SYSDATE
CREATE TABLE DEL_RECRUIT
( DEL_RECRUIT_NO    VARCHAR2(16)
, RECRUIT_NO        VARCHAR2(16) NOT NULL
, DEL_DATE          DATE         DEFAULT SYSDATE
, CONSTRAINT DEL_RECRUIT_NO_PK PRIMARY KEY(DEL_RECRUIT_NO)
, CONSTRAINT DEL_RECRUIT_NO_FK  FOREIGN KEY(RECRUIT_NO)
            REFERENCES RECRUIT(RECRUIT_NO)
);
--==>> Table DEL_RECRUIT이(가) 생성되었습니다.


-- 쪽지 이후
-- [33] DEL_NOTE 자진비활성화쪽지
-- 쪽지비활성화번호, 쪽지번호, 삭제일
-- NOTE_NO (FK, NN)
-- DEL_DATE     DEFAULT SYSDATE
CREATE TABLE DEL_NOTE
( DEL_NOTE_NO   VARCHAR2(16)
, NOTE_NO       VARCHAR2(16)    NOT NULL
, DEL_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT DEL_NOTE_NO_PK PRIMARY KEY(DEL_NOTE_NO)
, CONSTRAINT DEL_NOTE_NO_FK FOREIGN KEY(NOTE_NO)
            REFERENCES NOTE(NOTE_NO)       
);
--==>> Table DEL_NOTE이(가) 생성되었습니다.

--[34] 댓글 신고
CREATE TABLE REPORT_COMM
( REP_COMM_NO   NUMBER(10)
, COMM_NO       NUMBER(10)   NOT NULL
, PIN_NO        VARCHAR2(16) NOT NULL
, REP_DATE      DATE         DEFAULT SYSDATE
, REP_REASON_NO NUMBER(2)    NOT NULL
, CONSTRAINT REP_COMM_NO_PK PRIMARY KEY(REP_COMM_NO)
, CONSTRAINT REP_COMM_NO_FK FOREIGN KEY(COMM_NO)
                        REFERENCES COMMENTS(COMM_NO)
, CONSTRAINT REP_COMM_PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT COMM_REP_REASON_NO_FK FOREIGN KEY(REP_REASON_NO)
                        REFERENCES REPORT_REASON(REP_REASON_NO)
);
--==>> Table REPORT_COMM이(가) 생성되었습니다.


--[35] 댓글(자진)삭제
CREATE TABLE DEL_COMM
( DEL_COMM_NO   NUMBER(10)
, COMM_NO       NUMBER(10)      NOT NULL
, DEL_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT DEL_COMM_NO_PK PRIMARY KEY(DEL_COMM_NO)
, CONSTRAINT DEL_COMM_NO_FK FOREIGN KEY(COMM_NO)
                        REFERENCES COMMENTS(COMM_NO)
);
--==>> Table DEL_COMM이(가) 생성되었습니다.

--[36] 모집 포지션 지원
CREATE TABLE APPLY
( APPLY_NO          VARCHAR2(16)
, RECRUIT_POS_NO    VARCHAR2(20)        NOT NULL
, PIN_NO            VARCHAR2(16)        NOT NULL
, CONTENT           VARCHAR2(1500)      NOT NULL
, APPLY_DATE        DATE                DEFAULT SYSDATE
, CK_DATE           DATE
, CONSTRAINT APPLY_NO_PK PRIMARY KEY(APPLY_NO)
, CONSTRAINT APPLY_RECRUIT_POS_NO_FK FOREIGN KEY(RECRUIT_POS_NO)
                         REFERENCES RECRUIT_POS(RECRUIT_POS_NO)
, CONSTRAINT APPLY_PIN_NO_FK FOREIGN KEY(PIN_NO)
                        REFERENCES USER_PIN(PIN_NO)
);
--==>> Table APPLY이(가) 생성되었습니다.


-- 회원식별번호, 공고, 사유번호 이후
-- [37] REP_RECRUIT 모집공고신고
-- 공고신고번호, 공고번호, 회원식별번호, 작성일, 사유번호
-- RECRUIT_NO   (FK, NN)
-- PIN_NO (FK, NN)
-- CREATED_DATE     DEFAULT SYSDATE
-- REP_REASON_NO    (FK, NN)
CREATE TABLE REP_RECRUIT
( REP_RECRUIT_NO    VARCHAR2(16)
, RECRUIT_NO        VARCHAR2(16)    NOT NULL
, PIN_NO            VARCHAR2(16)    NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, REP_REASON_NO     NUMBER(2)       NOT NULL
, CONSTRAINT REP_RECRUIT_NO_PK PRIMARY KEY(REP_RECRUIT_NO)
, CONSTRAINT REP_RCRUIT_NO_FK FOREIGN KEY(RECRUIT_NO)
                REFERENCES RECRUIT(RECRUIT_NO)
, CONSTRAINT REP_RECRUIT_PIN_NO_FK  FOREIGN KEY(PIN_NO)
                REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT RECRUIT_REP_REASON_NO_FK FOREIGN KEY(REP_REASON_NO)
                REFERENCES REPORT_REASON(REP_REASON_NO)
);
--==>> Table REP_RECRUIT이(가) 생성되었습니다.



-- 회원식별번호, 쪽지, 사유번호 이후
-- [38] REPORT_NOTE 쪽지신고
-- 쪽지신고번호, 쪽지번호, 회원식별번호, 사유번호, 작성일
-- NOTE_NO  (FK, NN)
-- PIN_NO (FK, NN)
-- CREATED_DATE         DEFAULT SYSDATE
-- REP_REASON_NO    (FK, NN)
CREATE TABLE REPORT_NOTE
( REP_NOTE_NO       VARCHAR2(16)
, NOTE_NO           VARCHAR2(16)    NOT NULL
, PIN_NO            VARCHAR2(16)    NOT NULL
, REP_REASON_NO     NUMBER(2)       NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT REP_NOTE_NO_PK PRIMARY KEY(REP_NOTE_NO)
, CONSTRAINT REP_NOTE_NO_FK FOREIGN KEY(NOTE_NO)
                REFERENCES NOTE(NOTE_NO)
, CONSTRAINT REP_NOTE_PIN_NO_FK  FOREIGN KEY(PIN_NO)
                REFERENCES USER_PIN(PIN_NO)            
, CONSTRAINT NOTE_REP_REASON_NO_FK FOREIGN KEY(REP_REASON_NO)
                REFERENCES REPORT_REASON(REP_REASON_NO)
);
--==>> Table REPORT_NOTE이(가) 생성되었습니다.



--[39] 댓글 신고 처리
CREATE TABLE COMM_PRESULT
( PRESULT_NO    NUMBER(10)
, REP_COMM_NO   NUMBER(10) NOT NULL
, REP_RESULT_NO NUMBER(2) NOT NULL
, CONSTRAINT COMM_PRESULT_NO_PK PRIMARY KEY(PRESULT_NO)
, CONSTRAINT PRESULT_REP_COMM_NO_FK FOREIGN KEY(REP_COMM_NO)
                            REFERENCES REPORT_COMM(REP_COMM_NO)
, CONSTRAINT COMM_REP_RESULT_NO_FK FOREIGN KEY(REP_RESULT_NO)
                              REFERENCES REPORT_RESULT(REP_RESULT_NO)
);
--==>> Table COMM_PRESULT이(가) 생성되었습니다.

--[40] 1차 합류
CREATE TABLE FIRST_CK
( FIRST_CK_NO   VARCHAR2(16)
, APPLY_NO      VARCHAR2(16)    NOT NULL
, PASS_DATE     DATE            DEFAULT SYSDATE
, CONSTRAINT FIRST_CK_NO_PK PRIMARY KEY(FIRST_CK_NO)
, CONSTRAINT FIRST_CK_APPLY_NO_FK FOREIGN KEY(APPLY_NO)
                        REFERENCES APPLY(APPLY_NO)
);
--==>> Table FIRST_CK이(가) 생성되었습니다.


-- 지원서 이후
-- [41] DEL_APPLY 자진 비활성화 지원서
-- APPLY_NO (FK, NN)
-- DEL_DATE     DEFAULT SYSDATE
CREATE TABLE DEL_APPLY
( DEL_APPLY_NO  VARCHAR2(16)
, APPLY_NO      VARCHAR2(16)    NOT NULL
, DEL_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT DEL_APPLY_NO_PK PRIMARY KEY(DEL_APPLY_NO)
, CONSTRAINT DEL_APPLY_NO_FK FOREIGN KEY(APPLY_NO)
                        REFERENCES APPLY(APPLY_NO)
);
--==>> Table DEL_APPLY이(가) 생성되었습니다.



-- 공고신고, 처리결과번호 이후
-- [42] RECRUIT_PRESULT  공고신고처리(게시물)
-- 공고신고처리번호, 공고신고번호, 처리결과번호
-- REP_RECRUIT_NO (FK, NN)
-- REP_RESULT_NO (FK, NN)
CREATE TABLE RECRUIT_PRESULT
( PRESULT_NO        VARCHAR2(16)
, REP_RECRUIT_NO    VARCHAR2(16)    NOT NULL
, REP_RESULT_NO     NUMBER(2)       NOT NULL
, CONSTRAINT RECRUIT_PRESULT_NO_PK PRIMARY KEY(PRESULT_NO)
, CONSTRAINT REP_RECRUIT_NO_FK FOREIGN KEY(REP_RECRUIT_NO)
                               REFERENCES REP_RECRUIT(REP_RECRUIT_NO)
, CONSTRAINT RECRUIT_REP_RESULT_NO_FK FOREIGN KEY (REP_RESULT_NO)
                               REFERENCES REPORT_RESULT(REP_RESULT_NO)
);
--==>> Table RECRUIT_PRESULT이(가) 생성되었습니다.


-- 쪽지신고, 처리결과 이후
-- [43] NOTE_PRESULT 쪽지신고처리(게시물)
-- 쪽지신고처리번호, 쪽지신고번호, 처리결과번호
-- REP_NOTE_NO (FK, NN)
-- REP_RESULT_NO (FK, NN)
CREATE TABLE NOTE_PRESULT
( PRESULT_NO        VARCHAR2(16)
, REP_NOTE_NO       VARCHAR2(16)    NOT NULL
, REP_RESULT_NO     NUMBER(2)       NOT NULL
, CONSTRAINT NOTE_PRESULT_NO_PK PRIMARY KEY(PRESULT_NO)
, CONSTRAINT PRESULT_REP_NOTE_NO_FK FOREIGN KEY (REP_NOTE_NO)
                                    REFERENCES REPORT_NOTE(REP_NOTE_NO)
, CONSTRAINT NOTE_REP_RESULT_NO_FK FOREIGN KEY (REP_RESULT_NO)
                                    REFERENCES REPORT_RESULT(REP_RESULT_NO)
);
--==>> Table NOTE_PRESULT이(가) 생성되었습니다.

--[44] 최종 합류
CREATE TABLE FINAL
( FINAL_NO           VARCHAR2(16)
, FIRST_CK_NO        VARCHAR2(16)     NOT NULL
, FINAL_CK_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT FINAL_NO_PK PRIMARY KEY(FINAL_NO)
, CONSTRAINT FIRST_CK_NO_FK FOREIGN KEY(FIRST_CK_NO)
                            REFERENCES FIRST_CK(FIRST_CK_NO)
);
--==>> Table FINAL이(가) 생성되었습니다.

-- 제재, 재제기간, 쪽지신고처리 이후
-- [45] NOTE_URESULT 쪽지신고처리(피신고자)
-- 쪽지피신고자처리번호, 쪽지 신고처리번호, 제재내용번호, 제재기간번호, 제재일
-- PRESULT_NO   (FK, NN)
-- REGU_NO  (FK, NN)
-- RENU_PERIOD_NO (FK, NN)
-- REGU_DATE        DEFAULT SYSDATE
CREATE TABLE NOTE_URESULT
( URESULT_NO        VARCHAR2(16)
, PRESULT_NO        VARCHAR2(16)    NOT NULL
, REGU_NO           NUMBER(1)       NOT NULL
, REGU_PERIOD_NO    NUMBER(1)       NOT NULL
, REGU_DATE         DATE    DEFAULT SYSDATE
, CONSTRAINT NOTE_URESULT_NO_PK PRIMARY KEY(URESULT_NO)
, CONSTRAINT NOTE_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                            REFERENCES NOTE_PRESULT(PRESULT_NO)
, CONSTRAINT NOTE_REGU_NO_FK FOREIGN KEY(REGU_NO)
                            REFERENCES REGULATION(REGU_NO)
, CONSTRAINT NOTE_REGU_PERIOD_NO_FK FOREIGN KEY(REGU_PERIOD_NO)
                            REFERENCES REGULATION_PERIOD(REGU_PERIOD_NO)
);
--==>> Table NOTE_URESULT이(가) 생성되었습니다.


-- 지원서, 사유번호 뒤에 만들어져야하는 테이블
-- [46] REPORT_APPLY 지원서 신고
-- 지원서 신고번호, 모집포지션지원번호, 회원식별번호, 작성일, 사유번호
-- APPLY_NO (FK, NN)
-- PIN_NO (FK, NN)
-- CREATED_DATE     DEFAULT SYSDATE
-- REP_REASON_NO    (FK,NN)
CREATE TABLE REPORT_APPLY
( REP_APPLY_NO      VARCHAR2(16)
, APPLY_NO          VARCHAR2(16)     NOT NULL
, PIN_NO            VARCHAR2(16)     NOT NULL
, CREATED_DATE      DATE             DEFAULT SYSDATE
, REP_REASON_NO     NUMBER(2)        NOT NULL
, CONSTRAINT REP_APPLY_NO_PK PRIMARY KEY(REP_APPLY_NO)
, CONSTRAINT REP_APPLY_NO_FK FOREIGN KEY(APPLY_NO)
                             REFERENCES APPLY(APPLY_NO)
, CONSTRAINT REP_APPLY_PIN_NO_FK FOREIGN KEY(PIN_NO)
                             REFERENCES USER_PIN(PIN_NO)
, CONSTRAINT APPLY_REP_REASON_NO_FK FOREIGN KEY(REP_REASON_NO)
                                REFERENCES REPORT_REASON(REP_REASON_NO)
);
--==>> Table REPORT_APPLY이(가) 생성되었습니다.

-- 관리자, 쪽지, 쪽지신고처리이후
-- [47] DEL_REP_NOTE 쪽지삭제
-- 쪽지삭제번호, 쪽지신고처리번호, 관리자번호, 삭제일
-- PRESULT_NO (FK, NN)
-- ADMIN_NO (FK,NN)
-- DEL_DATE     DEFAULT SYSDATE
CREATE TABLE DEL_REP_NOTE
( DEL_NOTE_NO   VARCHAR2(16)
, PRESULT_NO    VARCHAR2(16)    NOT NULL
, ADMIN_NO      VARCHAR2(16)    NOT NULL
, DEL_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT DEL_REP_NOTE_NO_PK PRIMARY KEY(DEL_NOTE_NO)
, CONSTRAINT DEL_NOTE_PRESULT_NO_FK FOREIGN KEY (PRESULT_NO)
                             REFERENCES NOTE_PRESULT(PRESULT_NO)
, CONSTRAINT DEL_NOTE_ADMIN_NO_FK FOREIGN KEY (ADMIN_NO)
                              REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table DEL_REP_NOTE이(가) 생성되었습니다.

--[48] 댓글 신고 처리(피신고자)
CREATE TABLE COMM_URESULT
( URESULT_NO        NUMBER(10)
, PRESULT_NO        NUMBER(10)   NOT NULL
, REGU_NO           NUMBER(1)    NOT NULL
, REGU_PERIOD_NO    NUMBER(1)    NOT NULL
, REGU_DATE         DATE        DEFAULT SYSDATE
, CONSTRAINT COMM_URESULT_NO_PK PRIMARY KEY(URESULT_NO)
, CONSTRAINT COMM_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                                REFERENCES COMM_PRESULT(PRESULT_NO)
, CONSTRAINT COMM_REGU_NO_FK FOREIGN KEY(REGU_NO)
                                REFERENCES REGULATION(REGU_NO)
, CONSTRAINT COMM_REGU_PERIOD_NO_FK FOREIGN KEY(REGU_PERIOD_NO)
                                REFERENCES REGULATION_PERIOD(REGU_PERIOD_NO)
);
--==>> Table COMM_URESULT이(가) 생성되었습니다.


-- 재제, 제재기간, 공고신고처리 이후
-- [49] RECRUIT_URESULT 공고신고처리(피신고자)
-- 공고피신고자처리번호, 공고신고처리번호, 제재내용번호, 제재기간번호, 제재일
-- PRESULT_NO (FK, NN)
-- REGU_NO (FK, NN)
-- REGU_PERIOD_NO (FK, NN)
-- REDU_DATE        DEDAULT SYSDATE
CREATE TABLE RECRUIT_URESULT
( URESULT_NO        VARCHAR2(16)
, PRESULT_NO        VARCHAR2(16) NOT NULL
, REGU_NO           NUMBER(1)    NOT NULL
, REGU_PERIOD_NO    NUMBER(1)    NOT NULL
, REGU_DATE         DATE         DEFAULT SYSDATE
, CONSTRAINT RECRUIT_URESULT_NO_PK PRIMARY KEY(URESULT_NO)
, CONSTRAINT RECRUIT_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                                  REFERENCES RECRUIT_PRESULT(PRESULT_NO)
, CONSTRAINT RECRUIT_REGU_NO_FK FOREIGN KEY(REGU_NO)
                                REFERENCES REGULATION(REGU_NO)
, CONSTRAINT RECRUIT_REGU_PERIOD_NO_FK FOREIGN KEY(REGU_PERIOD_NO)
                                       REFERENCES REGULATION_PERIOD(REGU_PERIOD_NO) 
);
--==>> Table RECRUIT_URESULT이(가) 생성되었습니다.



--[50] 신고 댓글 삭제
CREATE TABLE DEL_REP_COMM
( DEL_COMM_NO   NUMBER(10)
, PRESULT_NO    NUMBER(10)       NOT NULL
, ADMIN_NO      VARCHAR2(16)     NOT NULL
, DEL_DATE      DATE             DEFAULT SYSDATE
, CONSTRAINT ADEL_COMM_NO_PK PRIMARY KEY(DEL_COMM_NO)
, CONSTRAINT ADEL_COMM_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                            REFERENCES COMM_PRESULT(PRESULT_NO)
, CONSTRAINT DEL_COMM_ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                                    REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table DEL_REP_COMM이(가) 생성되었습니다.



-- 관리자, 공고, 공고신고처리 이후
-- [51] DEL_REP_RECRUIT 공고글 삭제
-- 공고글 삭제번호, 공고신고처리번호, 관리자번호, 삭제일
-- PRESULT_NO (FK,NN)
-- ADMIN_NO (FK, NN)
-- DEL_DATE     DEFAULT SYSDATE
CREATE TABLE DEL_REP_RECRUIT
( DEL_RECRUIT_NO    VARCHAR2(16)    
, PRESULT_NO        VARCHAR2(16)     NOT NULL
, ADMIN_NO          VARCHAR2(16)     NOT NULL
, DEL_DATE          DATE             DEFAULT SYSDATE
, CONSTRAINT ADEL_RECRUIT_NO_PK PRIMARY KEY(DEL_RECRUIT_NO)
, CONSTRAINT ADEL_RECRUIT_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                                     REFERENCES RECRUIT_PRESULT(PRESULT_NO)
, CONSTRAINT DEL_RECRUIT_ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                                     REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table DEL_REP_RECRUIT이(가) 생성되었습니다.

-- 지원서 신고, 처리결과 이후 만들어져야하는 테이블
-- [52] APPLY_PRESULT 지원서 신고처리 (게시물)
-- 지원서 신고처리번호, 지원서 신고번호, 처리결과 번호
-- REP_APPLY_NO (FK, NN)
-- REP_RESULT_NO (FK, NN)
CREATE TABLE APPLY_PRESULT
( PRESULT_NO        VARCHAR2(16)
, REP_APPLY_NO      VARCHAR2(16)    NOT NULL
, REP_RESULT_NO     NUMBER(2)       NOT NULL
, CONSTRAINT PRESULT_NO_PK PRIMARY KEY(PRESULT_NO)
, CONSTRAINT PRESULT_REP_APPLY_NO_FK FOREIGN KEY(REP_APPLY_NO)
                                      REFERENCES REPORT_APPLY(REP_APPLY_NO)
, CONSTRAINT APPLY_REP_RESULT_NO_FK FOREIGN KEY (REP_RESULT_NO)
                                     REFERENCES REPORT_RESULT(REP_RESULT_NO)
);
--==>> Table APPLY_PRESULT이(가) 생성되었습니다.



-- 제재, 제재기간, 지원서 신고처리 이후
-- [53] APPLY_URESULT 지원서 신고처리 (유저)
-- 지원서 피신고자처리번호, 지원서 신고처리번호, 제재번호 , 제재기간번호, 제재일자
-- PRESULT_NO (FK, NN)
-- REGU_NO (FK, NN)
-- REGU_PERIOD_NO (FK, NN)
-- REGU_DATE        DEFAULT SYSDATE
CREATE TABLE APPLY_URESULT
( URESULT_NO        VARCHAR2(16)
, PRESULT_NO        VARCHAR2(16)    NOT NULL
, REGU_NO           NUMBER(1)       NOT NULL
, REGU_PERIOD_NO    NUMBER(1)       NOT NULL
, REGU_DATE         DATE            DEFAULT SYSDATE
, CONSTRAINT APPLY_URESULT_NO_PK PRIMARY KEY(URESULT_NO)
, CONSTRAINT APPLY_PRESULT_NO_FK FOREIGN KEY (PRESULT_NO)
                                REFERENCES APPLY_PRESULT (PRESULT_NO)
, CONSTRAINT APPLY_REGU_NO_FK FOREIGN KEY(REGU_NO)
                              REFERENCES REGULATION(REGU_NO)
, CONSTRAINT APPLY_REGU_PERIOD_NO_FK FOREIGN KEY(REGU_PERIOD_NO)
                               REFERENCES REGULATION_PERIOD(REGU_PERIOD_NO) 
);
--==>> Table APPLY_URESULT이(가) 생성되었습니다.

-- 관리자, 지원서, 지원신고처리 이후
-- [54] DEP_REP_APPLY 지원서 삭제
-- 지원서 삭제번호, 지원서 신고처리번호, 관리자번호, 삭제일
-- PRESULT_NO (FK, NN)
-- ADMIN_NO (FK, NN)
-- DEL_DATE     DEFAULT SYSDATE
CREATE TABLE DEL_REP_APPLY
( DEL_APPLY_NO   VARCHAR2(16)
, PRESULT_NO     VARCHAR2(16)    NOT NULL
, ADMIN_NO       VARCHAR2(16)    NOT NULL
, DEL_DATE       DATE            DEFAULT SYSDATE
, CONSTRAINT ADEL_APPLY_NO_PK PRIMARY KEY(DEL_APPLY_NO)
, CONSTRAINT ADEL_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                                REFERENCES APPLY_PRESULT(PRESULT_NO)
, CONSTRAINT DEL_APPLY_ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                                REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table DEL_REP_APPLY이(가) 생성되었습니다.


--[55] 프로젝트 개설 확정
CREATE TABLE PROJECT
( PRJ_NO        VARCHAR2(16)
, RECRUIT_NO    VARCHAR2(16)    NOT NULL
, PRJ_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT PRJ_NO_PK PRIMARY KEY(PRJ_NO)
, CONSTRAINT PRJ_RECRUIT_NO_FK FOREIGN KEY(RECRUIT_NO)
                                REFERENCES RECRUIT(RECRUIT_NO)
);
--===>> Table PROJECT이(가) 생성되었습니다.

-- 최종합류번호 이후에만 만들어지면 됨
-- [56] WORKSPACE (작업공간)
-- 작업공간번호, 최종합류번호, 제목, 내용, 작성일
-- FINAL_NO(FK,NN)
-- CREATED_DATE (NN) DEFAULT SYSDATE
CREATE TABLE WORKSPACE
( WORKSPACE_NO      VARCHAR2(16)
, FINAL_NO          VARCHAR2(16)    NOT NULL
, TITLE             VARCHAR2(100)   NOT NULL
, CONTENT           VARCHAR2(2000)  NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT WORKSPACE_NO_PK PRIMARY KEY(WORKSPACE_NO)
, CONSTRAINT WORKSPACE_FINAL_NO_FK    FOREIGN KEY(FINAL_NO)
                                    REFERENCES FINAL(FINAL_NO)
);
--==>> Table WORKSPACE이(가) 생성되었습니다.

-- 최종합류번호 이후에만 만들어지면 됨
-- [57] SPACE_NOTICE (팀 공지게시판)
-- 공지게시판번호, 프로젝트번호, 제목, 내용, 작성일
-- PRJ_NO (FK,NN)
-- CREATED_DATE (NN) DEFAULT SYSDATE
CREATE TABLE SPACE_NOTICE
( SPACE_NOTICE_NO   VARCHAR2(16)
, PRJ_NO            VARCHAR2(16)    NOT NULL
, TITLE             VARCHAR2(100)   NOT NULL
, CONTENT           VARCHAR2(1000)  NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT SPACE_NOTICE_NO_PK PRIMARY KEY(SPACE_NOTICE_NO)
, CONSTRAINT SPACE_NOTICE_PRJ_NO_FK  FOREIGN KEY(PRJ_NO)
                                    REFERENCES PROJECT(PRJ_NO)
);
--==>> Table SPACE_NOTICE이(가) 생성되었습니다.


-- 최종합류테이블 이후에만 만들어지면 됨
-- [58] MEETING (회의록)
-- 회의록 번호, 최종합류번호, 제목, 내용, 첨부파일경로, 게시판작성일, 회의일자
-- FINAL_NO (FK,NN)
-- FILE..????
-- CREATED_DATE (NN)    DEFAULT SYSDATE
-- MEETING_DATE (NN)    DEFAULT SYSDATE ※
CREATE TABLE MEETING
( MEETING_NO        VARCHAR2(20)
, FINAL_NO          VARCHAR2(16)        NOT NULL
, TITLE             VARCHAR2(100)       NOT NULL
, CONTENT           VARCHAR2(1000)      NOT NULL
, FILEURL           VARCHAR2(400)
, CREATED_DATE      DATE               DEFAULT SYSDATE
, MEETING_DATE      DATE               DEFAULT SYSDATE
, CONSTRAINT MEETING_NO_PK PRIMARY KEY(MEETING_NO)
, CONSTRAINT MEETING_FINAL_NO_FK FOREIGN KEY(FINAL_NO)
                                 REFERENCES FINAL(FINAL_NO)
);
--==>> Table MEETING이(가) 생성되었습니다.



-- 최종합류테이블 이후에만 생성하면 됨
-- [59] FEED (담벼락)
-- 피드번호, 최종합류번호, 내용, 작성일
-- FINAL_NO (FK,NN)
-- CREATED_DATE     DEFAULT SYSDATE
CREATE TABLE FEED
( FEED_NO           NUMBER(10)
, FINAL_NO          VARCHAR2(16)    NOT NULL
, CONTENT           VARCHAR2(100)   NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT FEED_NO_PK PRIMARY KEY(FEED_NO)
, CONSTRAINT FEED_FINAL_NO_FK    FOREIGN KEY(FINAL_NO)
                                 REFERENCES FINAL(FINAL_NO)
);
--==>> Table FEED이(가) 생성되었습니다.


--[60] 프로젝트 중단
CREATE TABLE PROJECT_STOP
( PRJ_STOP_NO       VARCHAR2(16)   
, PRJ_NO            VARCHAR2(16)    NOT NULL
, STOP_DATE         DATE            DEFAULT SYSDATE
, STOP_REASON_NO    NUMBER(1)       NOT NULL
, CONSTRAINT PRJ_STOP_NO_PK PRIMARY KEY(PRJ_STOP_NO)
, CONSTRAINT STOP_PRJ_NO_FK FOREIGN KEY(PRJ_NO)
                            REFERENCES PROJECT(PRJ_NO)
, CONSTRAINT STOP_REASON_NO_FK FOREIGN KEY(STOP_REASON_NO)
                              REFERENCES PRJ_STOP_REASON(STOP_REASON_NO)
);
--==>> Table PROJECT_STOP이(가) 생성되었습니다.


--[61] 프로젝트 개인 이탈
CREATE TABLE MEMBER_OUT
( MEM_OUT_NO        VARCHAR2(16)      
, FINAL_NO          VARCHAR2(16)    NOT NULL
, OUT_REASON_NO     NUMBER(1)       NOT NULL
, OUT_DATE          DATE            DEFAULT SYSDATE
, CONSTRAINT MEM_OUT_NO_PK PRIMARY KEY(MEM_OUT_NO)
, CONSTRAINT MEM_OUT_FINAL_NO_FK FOREIGN KEY(FINAL_NO)
                                 REFERENCES FINAL(FINAL_NO)
, CONSTRAINT OUT_REASON_NO_FK FOREIGN KEY(OUT_REASON_NO)
                              REFERENCES MEM_OUT_REASON(OUT_REASON_NO)
);
--==>> Table MEMBER_OUT이(가) 생성되었습니다.

-- 최종합류번호, 작업공간 생성 이후 만들어지면 됨
-- [62] WORKSPACE_COMM (작업공간 댓글)
-- 작업공간댓글번호, 작업공간번호, 최종합류번호, 내용, 작성일
-- WORKSPACE_NO (FK, NN)
-- FINAL_NO (FK, NN)
-- CREATED_DATE (NN) DEFAULT SYSDATE
CREATE TABLE WORKSPACE_COMM
( WORKSPACE_COMM_NO NUMBER(10)
, WORKSPACE_NO      VARCHAR2(16)    NOT NULL      
, FINAL_NO          VARCHAR2(16)    NOT NULL
, CONTENT           VARCHAR2(400)   NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT WORKSPACE_COMM_NO_PK PRIMARY KEY(WORKSPACE_COMM_NO)
, CONSTRAINT WORKSPACE_COMM_FINAL_NO_FK FOREIGN KEY(FINAL_NO)
                         REFERENCES FINAL(FINAL_NO)
, CONSTRAINT COMM_WORKSPACE_NO_FK FOREIGN KEY(WORKSPACE_NO)
                            REFERENCES WORKSPACE(WORKSPACE_NO)
);
--==>> Table WORKSPACE_COMM이(가) 생성되었습니다.



-- 최종합류번호, 프로젝트 이후
-- [63] REPORT_PRJ 프로젝트 신고
-- 프로젝트신고번호, 프로젝트번호, 최종합류번호, 프로젝트 신고사유번호, 작성일
-- PRJ_NO (FK, NN)
-- FINAL_NO (FK, NN)
-- REP_REASON_NO (FK, NN)
-- CREATED_DATE     DEFAULT SYSDATE
CREATE TABLE REPORT_PRJ
( REP_PRJ_NO        VARCHAR2(16)
, PRJ_NO            VARCHAR2(16)    NOT NULL
, FINAL_NO          VARCHAR2(16)    NOT NULL
, REP_REASON_NO      NUMBER(2)        NOT NULL
, CREATED_DATE      DATE            DEFAULT SYSDATE
, CONSTRAINT REP_PRJ_NO_PK PRIMARY KEY(REP_PRJ_NO)
, CONSTRAINT REP_PRJ_NO_FK FOREIGN KEY(PRJ_NO)
                            REFERENCES PROJECT(PRJ_NO)
, CONSTRAINT REP_PRJ_FINAL_NO_FK FOREIGN KEY (FINAL_NO)
                                 REFERENCES FINAL(FINAL_NO)
, CONSTRAINT PRJ_REP_REASON_NO_FK  FOREIGN KEY (REP_REASON_NO)
                                  REFERENCES REP_PRJ_REASON(REP_REASON_NO)
);
--==>> Table REPORT_PRJ이(가) 생성되었습니다.


-- 관리자, 처리결과, 프로젝트 신고 이후
-- [64] PRJ_PRESULT 프로젝트 신고처리
-- 프로젝트 신고처리번호, 프로젝트 신고접수번호, 처리결과번호, 관리자번호, 처리일시
-- REP_PRJ_NO (FK, NN)
-- REP_RESULT_NO (FK, NN)
-- ADMIN_NO (FK, NN)
-- DATE     DEFAULT SYSDATE
CREATE TABLE PRJ_PRESULT  
( PRESULT_NO    VARCHAR2(16)
, REP_PRJ_NO    VARCHAR2(16)    NOT NULL
, REP_RESULT_NO  NUMBER(2)       NOT NULL
, ADMIN_NO      VARCHAR2(16)    NOT NULL
, CREATED_DATE   DATE            DEFAULT SYSDATE
, CONSTRAINT PRJ_PRESULT_NO_PK PRIMARY KEY(PRESULT_NO)
, CONSTRAINT PRESULT_REP_PRJ_NO_FK FOREIGN KEY(REP_PRJ_NO)
                                   REFERENCES REPORT_PRJ(REP_PRJ_NO)
, CONSTRAINT PRJ_REP_RESULT_NO_FK FOREIGN KEY(REP_RESULT_NO)
                                  REFERENCES REPORT_RESULT(REP_RESULT_NO)
, CONSTRAINT PRJ_PRESULT_ADMIN_NO_FK FOREIGN KEY(ADMIN_NO)
                                  REFERENCES ADMIN(ADMIN_NO)
);
--==>> Table PRJ_PRESULT이(가) 생성되었습니다.

-- 프로젝트신고처리 이후
-- [65] DEL_REP_PRJ 정지된 프로젝트
-- 정지된 프로젝트번호, 프로젝트 신고처리번호 
-- PRESULT_NO (FK, NN)
CREATE TABLE DEL_REP_PRJ
( DEL_PRJ_NO    VARCHAR2(16)
, PRESULT_NO    VARCHAR2(16)    NOT NULL
, CONSTRAINT ADEL_PRJ_NO_PK PRIMARY KEY(DEL_PRJ_NO)
, CONSTRAINT DEL_PRJ_PRESULT_NO_FK FOREIGN KEY(PRESULT_NO)
                                    REFERENCES PRJ_PRESULT(PRESULT_NO)
);
--==>> Table DEL_REP_PRJ이(가) 생성되었습니다.

-- 평가 테이블들은 거의 마지막에 만들어져야 함

-- [66] PROJECT_RATE (프로젝트 완료평가)
-- 프로젝트 완료평가번호, 평가자, 피평가자, 평가선택지번호, 평가일
-- 평가자, 피평가자 (FINAL_NO) (FK, NN)
-- RATE_NO (FK, NN)
-- RATE_DATE    DEFAULT SYSDATE
CREATE TABLE PROJECT_RATE
( DONE_RATE_NO  VARCHAR2(20)
, GIVER         VARCHAR2(16)    NOT NULL
, RECEIVER      VARCHAR2(16)    NOT NULL
, RATE_NO       NUMBER(1)       NOT NULL
, RATE_DATE     DATE            DEFAULT SYSDATE
, CONSTRAINT DONE_RATE_NO_PK PRIMARY KEY(DONE_RATE_NO)
, CONSTRAINT GIVER_FK FOREIGN KEY(GIVER)
                       REFERENCES FINAL(FINAL_NO)
, CONSTRAINT RECEIVER_FK FOREIGN KEY(RECEIVER)
                       REFERENCES FINAL(FINAL_NO)
, CONSTRAINT RATE_NO_FK FOREIGN KEY(RATE_NO)
                        REFERENCES RATE_SELECT(RATE_NO)
);
--==>> Table PROJECT_RATE이(가) 생성되었습니다.


-- [67] PROJECT_STOP_RATE 프로젝트 중단평가
-- 프로젝트 중단평가번호, 프로젝트 중단번호, 평가자, 피평가자, 평가선택지번호, 평가일
-- 평가자, 피평가자 (FINAL_NO) (FK, NN)
-- PRJ_STOP_NO (FK, NN)
-- RATE_NO (FK, NN)
-- RATE_DATE    DEFAULT SYSDATE
CREATE TABLE PROJECT_STOP_RATE
( STOP_RATE_NO  VARCHAR2(20)
, PRJ_STOP_NO   VARCHAR2(16)    NOT NULL
, RECEIVER      VARCHAR2(16)    NOT NULL
, GIVER         VARCHAR2(16)    NOT NULL
, RATE_NO       NUMBER(1)       NOT NULL
, RATE_DATE     DATE            DEFAULT SYSDATE
, CONSTRAINT STOP_RATE_NO_PK PRIMARY KEY(STOP_RATE_NO)
, CONSTRAINT PRJ_STOP_NO_FK FOREIGN KEY(PRJ_STOP_NO)
                            REFERENCES PROJECT_STOP(PRJ_STOP_NO)
, CONSTRAINT STOP_GIVER_FK FOREIGN KEY(GIVER)
                           REFERENCES FINAL(FINAL_NO)
, CONSTRAINT STOP_RECEIVER_FK FOREIGN KEY(RECEIVER)
                             REFERENCES FINAL(FINAL_NO)
, CONSTRAINT STOP_RATE_NO_FK FOREIGN KEY(RATE_NO)
                             REFERENCES RATE_SELECT(RATE_NO)
);
--==>> Table PROJECT_STOP_RATE이(가) 생성되었습니다.


-- [68] MEM_OUT_RATE 개인이탈평가
-- 개인이탈 평가번호, 프로젝트 이탈번호, 평가자, 평가선택지번호, 평가일
-- MEM_OUT_NO (FK,NN)
-- GIVER (FK, NN)  (FINAL_NO)
-- RATE_DATE    DEFAULT SYSDATE
CREATE TABLE MEM_OUT_RATE
( OUT_RATE_NO   VARCHAR2(18)
, MEM_OUT_NO    VARCHAR2(16)    NOT NULL
, GIVER         VARCHAR2(16)    NOT NULL
, RATE_NO       NUMBER(1)       NOT NULL
, RATE_DATE     DATE            DEFAULT SYSDATE
, CONSTRAINT OUT_RATE_NO_PK PRIMARY KEY(OUT_RATE_NO)
, CONSTRAINT OUT_MEM_OUT_NO_FK FOREIGN KEY(MEM_OUT_NO)
                            REFERENCES MEMBER_OUT(MEM_OUT_NO)
, CONSTRAINT OUT_GIVER_FK FOREIGN KEY(GIVER)
                             REFERENCES FINAL(FINAL_NO)
, CONSTRAINT OUT_RATE_NO_FK FOREIGN KEY(RATE_NO)
                            REFERENCES RATE_SELECT(RATE_NO)
);
--==>> Table MEM_OUT_RATE이(가) 생성되었습니다.



--[31-1] 모집 사용 도구
CREATE TABLE RECRUIT_TOOL
( RECRUIT_TOOL_NO       VARCHAR2(20)
, RECRUIT_NO            VARCHAR2(16) NOT NULL
, TOOL_NO               NUMBER(3)    NOT NULL
, CONSTRAINT RECRUIT_TOOL_NO_PK PRIMARY KEY(RECRUIT_TOOL_NO)
, CONSTRAINT TOOL_RECRUIT_NO_FK FOREIGN KEY(RECRUIT_NO)
                                REFERENCES RECRUIT(RECRUIT_NO)
, CONSTRAINT RECRUIT_TOOL_NO_FK FOREIGN KEY(TOOL_NO)
                                REFERENCES TOOL(TOOL_NO)                
);
--==>> Table RECRUIT_TOOL이(가) 생성되었습니다.



--==>> 모두 입력 완료