SELECT USER
FROM DUAL;
--==>> PROJECTORS

SELECT SYSDATE
FROM DUAL;
--==>> 2023-08-07

-- 관리자 조회 (로그인시) 쿼리문
-- DELETEDATE 가 0이면 활성화 관리자, 1이면 비활성화 관리자
SELECT NVL2(TO_CHAR(QA.QUIT_DATE,'YYYY-MM-DD'),0,1) AS DELETEDATE, AD.PIN_NO AS PIN_NO, AD.ADMIN_NO AS ADMIN_NO, COUNT(*) AS COUNT
FROM QUIT_ADMIN QA
RIGHT JOIN ADMIN AD 
ON QA.PIN_NO = AD.PIN_NO
WHERE AD.ADMIN_ID = 'admin001@gmail.com' AND AD.ADMIN_PW = 'admin001'
GROUP BY TO_CHAR(QA.QUIT_DATE,'YYYY-MM-DD'), AD.PIN_NO, AD.ADMIN_NO;

-- 관리자 로그인 기록 쿼리문
DESC LOGIN_REC;

SELECT *
FROM LOGIN_REC;

INSERT INTO LOGIN_REC(LOGIN_REC,PIN_NO) 
VALUES(LOGINRECSEQ.NEXTVAL, 'UP1' )
;

ROLLBACK;

--------------------------------------------------------------------------------

-- 금일 로그인 횟수
SELECT COUNT(*)
FROM LOGIN_REC
WHERE TO_CHAR(LOGIN_DATE, 'YYYY-MM-DD')=TO_CHAR(SYSDATE,'YYYY-MM-DD');

DESC REPORT_COMM;

-- 처리해야할 신고 건수
-- 댓글
SELECT COUNT(CASE WHEN RCR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
FROM REP_COMM_RESULT RCR
JOIN REPORT_COMM RC
ON RCR.REP_COMM_NO = RC.REP_COMM_NO;
-- 지원
SELECT COUNT(CASE WHEN RAR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
FROM REP_APPLY_RESULT RAR
JOIN REPORT_APPLY RA
ON RAR.REP_APPLY_NO = RA.REP_APPLY_NO;
-- 공고
SELECT COUNT(CASE WHEN RRR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
FROM REP_RECRUIT_RESULT RRR
JOIN REP_RECRUIT RR
ON RRR.REP_RECRUIT_NO = RR.REP_RECRUIT_NO;
-- 쪽지
SELECT COUNT(CASE WHEN RNR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
FROM REP_NOTE_RESULT RNR
JOIN REPORT_NOTE RN
ON RNR.REP_NOTE_NO = RN.REP_NOTE_NO;

-- 댓글 + 지원 + 공고 + 쪽지
SELECT
  (
    SELECT COUNT(CASE WHEN RCR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
    FROM REP_COMM_RESULT RCR
    RIGHT JOIN REPORT_COMM RC
    ON RCR.REP_COMM_NO = RC.REP_COMM_NO
  ) +
  (
    SELECT COUNT(CASE WHEN RAR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
    FROM REP_APPLY_RESULT RAR
    RIGHT JOIN REPORT_APPLY RA
    ON RAR.REP_APPLY_NO = RA.REP_APPLY_NO
  ) +
  (
    SELECT COUNT(CASE WHEN RRR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
    FROM REP_RECRUIT_RESULT RRR
    RIGHT JOIN REP_RECRUIT RR
    ON RRR.REP_RECRUIT_NO = RR.REP_RECRUIT_NO
  ) +
  (
    SELECT COUNT(CASE WHEN RNR.REGU_DATE IS NULL THEN 1 END) AS NULL_COUNT
    FROM REP_NOTE_RESULT RNR
    RIGHT JOIN REPORT_NOTE RN
    ON RNR.REP_NOTE_NO = RN.REP_NOTE_NO
  ) AS TOTAL_REPORT_COUNT
FROM DUAL;

-- 처리해야할 문의건수
SELECT COUNT(CASE WHEN A.CREATED_DATE IS NULL THEN 1 END)AS NULL_COUNT
FROM QUESTION Q
JOIN ANSWER A
ON Q.QUESTION_NO = A.QUESTION_NO;


-----------------------------------------------------------------------------------
-- ADMIN 공지 관련 쿼리문

-- 공지 LIST 조회 구문

SELECT ADMIN_NOTICE_NO
        , SUBSTR(( SELECT ADMIN_NO
            FROM ADMIN
            WHERE PIN_NO = AN.PIN_NO),3) AS ADMIN_NO
        , TITLE
        , CONTENT
FROM ADMIN_NOTICE AN
;

-- 공지 insert구문
INSERT INTO ADMIN_NOTICE(ADMIN_NOTICE_NO, PIN_NO, TITLE, CONTENT)
VALUES(AD||ADMINNOSEQ.NEXTVAL, ?, ? , ? )
;

-- 공지 DELETE 구문
DELETE
FROM ADMIN_NOTICE
WHERE ADMIN_NOTICE = ? ;


-- pin_no 로 관리자번호 뒷자리 숫자만 조회
SELECT TO_NUMBER(SUBSTR(ADMIN_NO, 3)) AS ADMIN_NO
FROM ADMIN
WHERE PIN_NO = 'UP16';
