SELECT USER
FROM DUAL;
--==>> PROJECTORS

SELECT SYSDATE
FROM DUAL;
--==>> 2023-08-07

-- 관리자 조회 (로그인시) 쿼리문
-- DELETEDATE 가 0이면 활성화 관리자, 1이면 비활성화 관리자
SELECT NVL2(TO_CHAR(QA.QUIT_DATE,'YYYY-MM-DD'),0,1) AS DELETEDATE, AD.PIN_NO AS PIN_NO, AD.ADMIN_NO AS ADMIN_NO, COUNT(*) AS COUNT
FROM QUIT_ADMIN QA
RIGHT JOIN ADMIN AD 
ON QA.PIN_NO = AD.PIN_NO
WHERE AD.ADMIN_ID = 'admin001@gmail.com' AND AD.ADMIN_PW = 'admin001'
GROUP BY TO_CHAR(QA.QUIT_DATE,'YYYY-MM-DD'), AD.PIN_NO, AD.ADMIN_NO;

-- 관리자 로그인 기록 쿼리문
DESC LOGIN_REC;

SELECT *
FROM LOGIN_REC;

INSERT INTO LOGIN_REC(LOGIN_REC,PIN_NO) 
VALUES(LOGINRECSEQ.NEXTVAL, 'UP1' )
;

ROLLBACK;

--------------------------------------------------------------------------------

-- 금일 로그인 횟수
SELECT COUNT(*)
FROM LOGIN_REC
WHERE TO_CHAR(LOGIN_DATE, 'YYYY-MM-DD')=TO_CHAR(SYSDATE,'YYYY-MM-DD');

DESC REPORT_COMM;

-- 처리해야할 문의 건수


-- 처리해야할 신고건수