-- ※ 관리자 관련 INSERT 구문

-- 회원 식별번호 생성
-- ⓞ
INSERT INTO USER_PIN(PIN_NO, JOIN_DATE) VALUES(UP||TO_CHAR(USERPINSEQ.NEXTVAL),SYSDATE);

-- 관리자 시퀀스 생성
CREATE SEQUENCE ADMINNOSEQ
NOCACHE;

-- 관리자 INSERT 구문 ⓞ 번 실행 후에 번호 INSERT 구문 실행하기
-- ①
INSERT INTO ADMIN(ADMIN_NO, ADMIN_ID, ADMIN_PW, REG_DATE, PIN_NO) 
VALUES (AD||TO_CHAR(ADMINNOSEQ.NEXTVAL), 'admin001@gmail.com'
, CRYPTPACK.ENCRYPT('admin001','java002$'), SYSDATE, '생성한 핀넘버 넣기');

--②
INSERT INTO ADMIN(ADMIN_NO, ADMIN_ID, ADMIN_PW, REG_DATE, PIN_NO) 
VALUES (AD||TO_CHAR(ADMINNOSEQ.NEXTVAL), 'admin002@gmail.com'
, CRYPTPACK.ENCRYPT('admin002','java002$'), SYSDATE, '생성한 핀넘버 넣기');


SELECT *
FROM POSITION;

-- ※ 회원 관련 INSERT 구문

-- 회원 INSERT 구문 ⓞ 번 실행 후에 번호 INSERT 구문 실행하기
-- ①
-- 유저 정보
INSERT INTO USERS(USER_NO, PIN_NO, ID, PW, NICKAME, PHOTOURL)
VALUES (US||TO_CHAR(USERNOSEQ.NEXTVAL), '핀넘버들어갈자리' , 'hwangi@gmail.com', 'java002$', '환기', 'images/defaulfPhoto.jpg ');
-- 프로필
INSERT INTO PROFILE(PROFILE_NO, PIN_NO, POS_NO, SUB_REGION_NO, PROFILE_DATE)
VALUES (PF||TO_CHAR(PROFILESEQ.NEXTVAL), '핀넘버들어갈자리', 2, 901, SYSDATE);
-- 유저 사용언어 + 환경
INSERT INTO USER_TOOL(UTOOL_NO, PROFILE_NO, TOOL_NO)
VALUES (UT||TO_CHAR(UTOOLNOSEQ.NEXTVAL), '프로필넘버들어갈자리', 1);
INSERT INTO USER_TOOL(UTOOL_NO, PROFILE_NO, TOOL_NO)
VALUES (UT||TO_CHAR(UTOOLNOSEQ.NEXTVAL), '프로필넘버들어갈자리', 11);
INSERT INTO USER_TOOL(UTOOL_NO, PROFILE_NO, TOOL_NO)
VALUES (UT||TO_CHAR(UTOOLNOSEQ.NEXTVAL), '프로필넘버들어갈자리', 21);
-- 모집공고 작성
INSERT INTO RECRUIT(RECRUIT_NO, PIN_NO, DO_TYPE_NO, TITLE, CONTENT, CREATED_DATE, PRJ_START, PRJ_END)
VALUES (RC||TO_CHAR(RECRUITNOSEQ.NEXTVAL), '핀넘버들어갈자리', 0, '라흐헤스트 모집공고', '저희 라흐헤스트는 이런저런거 하려고 생각하고 있습니다'
, SYSDATE, TO_DATE('2023-08-25'), TO_DATE('2023-12-25'));
-- 모집공고에 대한 포지션 작성
INSERT INTO RECRUIT_POS(RECRUIT_POS_NO, RECRUIT_NO, POS_NO)
VALUES (RP||TO_CHAR(RECRUITPOSNOSEQ.NEXTVAL), '모집공고들어갈자리', 1);
INSERT INTO RECRUIT_POS(RECRUIT_POS_NO, RECRUIT_NO, POS_NO)
VALUES (RP||TO_CHAR(RECRUITPOSNOSEQ.NEXTVAL), '모집공고들어갈자리', 1);
INSERT INTO RECRUIT_POS(RECRUIT_POS_NO, RECRUIT_NO, POS_NO)
VALUES (RP||TO_CHAR(RECRUITPOSNOSEQ.NEXTVAL), '모집공고들어갈자리', 2);
-- 모집공고에 대한 기술 작성
--???? 빠져있네
-- 팀장은 자연스럽게 지원한 상태 됨
INSERT INTO APPLY(APPLY_NO, RECRUIT_POS_NO, PIN_NO, CONTENT, APPLY_DATE, CK_DATE)
VALUES(AP||TO_CHAR(APPLYNOSEQ.NEXTVAL), '모집자모집포지션넘버들어갈자리', '모집자회원식별번호들어갈자리', '팀장', SYSDATE, SYSDATE+1);
-- 스무스하게 1차합류까지 자동으로 수락된 상황
INSERT INTO FIRST_CK (FIRST_CK_NO, APPLY_NO, PASS_DATE)
VALUES (FS||TO_CHAR(FIRSTCHECKNOSEQ.NEXTVAL), '모집자의지원번호', SYSDATE+1);