SELECT USER
FROM DUAL;
--==>> PROJECTORS

--==[1. 이준복]
관리자  ->          AD||SEQ
회원식별번호        UP||SEQ
유저    ->          US||SEQ
프로필  ->          PF||SEQ
유저 사용 도구  ->  UT||SEQ
공지    ->          NT||SEQ
공고    ->          RC||SEQ
지원서  ->          AP||SEQ
프로젝트->          PJ||SEQ
모집 포지션 번호 -> RP||SEQ
1차 합류 번호    -> FS||SEQ
최종 합류 번호   -> FN||SEQ

회원 5명
모집 공고 2개 (1모집중|1모집완료)
지원서 5개 (모집자 본인 지원서 2 + 지원자 3개(지원서 2개는 모집 완료 1개는 모집 중)) 
프로젝트(1 3인 프로젝트)
================================

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

=============================
CREATE SEQUENCE USERPINSEQ
NOCACHE;

CREATE SEQUENCE USERNOSEQ
NOCACHE;

CREATE SEQUENCE PROFILENOSEQ
NOCACHE;

CREATE SEQUENCE UTOOLNOSEQ
NOCACHE;

CREATE SEQUENCE RECRUITNOSEQ
NOCACHE;

CREATE SEQUENCE APPLYNOSEQ
NOCACHE;

CREATE SEQUENCE RECRUITPOSSEQ
NOCACHE;

CREATE SEQUENCE FIRSTCKSEQ
NOCACHE;

CREATE SEQUENCE FINALNOSEQ
NOCACHE;

CREATE SEQUENCE PROJECTNOSEQ
NOCACHE;

--===============[회원 정보 INSERT]
INSERT INTO USER_PIN
(PIN_NO, JOIN_DATE) 
VALUES
( 'UP'||TO_CHAR(USERPINSEQ.NEXTVAL)
, SYSDATE);

INSERT INTO USERS
( USER_NO
, PIN_NO
, ID
, PW
, NICKNAME
, PHOTOURL)
VALUES
( 'US''||TO_CHAR(USERNOSEQ.NEXTVAL)  
, (SELECT PIN_NO
   FEOM USER_PIN
   ORDER BY JOIN_DATE DESC
   FETCH FIRST 1 ROW ONLY;)
, '도라에몽@naver.com'
, 'java002$'
, '도라에몽'
, 'c://WebStudy');


INSERT INTO USER_PIN
(PIN_NO, JOIN_DATE) 
VALUES
( 'UP'||TO_CHAR(USERPINSEQ.NEXTVAL)
, SYSDATE);

INSERT INTO USERS
( USER_NO
, PIN_NO
, ID
, PW
, NICKNAME
, PHOTOURL)
VALUES
( 'US''||TO_CHAR(USERNOSEQ.NEXTVAL)  
, (SELECT PIN_NO
   FEOM USER_PIN
   ORDER BY JOIN_DATE DESC
   FETCH FIRST 1 ROW ONLY;)
, '노진구@naver.com'
, 'java002$'
, '노진구'
, 'c://WebStudy');

INSERT INTO USER_PIN
(PIN_NO, JOIN_DATE) 
VALUES
( 'UP'||TO_CHAR(USERPINSEQ.NEXTVAL)
, SYSDATE);

INSERT INTO USERS
( USER_NO
, PIN_NO
, ID
, PW
, NICKNAME
, PHOTOURL)
VALUES
( 'US''||TO_CHAR(USERNOSEQ.NEXTVAL)  
, (SELECT PIN_NO
   FEOM USER_PIN
   ORDER BY JOIN_DATE DESC
   FETCH FIRST 1 ROW ONLY;)
, '비실이@naver.com'
, 'java002$'
, '비실이'
, 'c://WebStudy');

INSERT INTO USER_PIN
(PIN_NO, JOIN_DATE) 
VALUES
( 'UP'||TO_CHAR(USERPINSEQ.NEXTVAL)
, SYSDATE);

INSERT INTO USERS
( USER_NO
, PIN_NO
, ID
, PW
, NICKNAME
, PHOTOURL)
VALUES
( 'US''||TO_CHAR(USERNOSEQ.NEXTVAL)  
, (SELECT PIN_NO
   FEOM USER_PIN
   ORDER BY JOIN_DATE DESC
   FETCH FIRST 1 ROW ONLY;)
, '퉁퉁이@naver.com'
, 'java002$'
, '퉁퉁이'
, 'c://WebStudy');


INSERT INTO USER_PIN
(PIN_NO, JOIN_DATE) 
VALUES
( 'UP'||TO_CHAR(USERPINSEQ.NEXTVAL)
, SYSDATE);

INSERT INTO USERS
( USER_NO
, PIN_NO
, ID
, PW
, NICKNAME
, PHOTOURL)
VALUES
( 'US''||TO_CHAR(USERNOSEQ.NEXTVAL)  
, (SELECT PIN_NO
   FEOM USER_PIN
   ORDER BY JOIN_DATE DESC
   FETCH FIRST 1 ROW ONLY;)
, '이슬이@naver.com'
, 'java002$'
, '이슬이'
, 'c://WebStudy');


--[회원 프로필 INSERT]====================

INSERT INTO PROFILE
( PROFILE_NO
, PIN_NO
, POS_NO
, SUB_REGION_NO
, PROFILE_DATE)
VALUES
( 'PF'||TO_CHAR(PROFILESEQ.NEXTVAL)
, SELECT PIN_NO
  FROM USERS
  WHERE NICKNAME='도라에몽')
, 1
, 16
, SYSDATE);


INSERT INTO PROFILE
( PROFILE_NO
, PIN_NO
, POS_NO
, SUB_REGION_NO
, PROFILE_DATE)
VALUES
( 'PF'||TO_CHAR(PROFILESEQ.NEXTVAL)
, SELECT PIN_NO
  FROM USERS
  WHERE NICKNAME='노진구')
, 2
, 30
, SYSDATE);

INSERT INTO PROFILE
( PROFILE_NO
, PIN_NO
, POS_NO
, SUB_REGION_NO
, PROFILE_DATE)
VALUES
( 'PF'||TO_CHAR(PROFILESEQ.NEXTVAL)
, SELECT PIN_NO
  FROM USERS
  WHERE NICKNAME='비실이')
, 3
, 7
, SYSDATE);

INSERT INTO PROFILE
( PROFILE_NO
, PIN_NO
, POS_NO
, SUB_REGION_NO
, PROFILE_DATE)
VALUES
( 'PF'||TO_CHAR(PROFILESEQ.NEXTVAL)
, SELECT PIN_NO
  FROM USERS
  WHERE NICKNAME='퉁퉁이')
, 4
, 12
, SYSDATE);

INSERT INTO PROFILE
( PROFILE_NO
, PIN_NO
, POS_NO
, SUB_REGION_NO
, PROFILE_DATE)
VALUES
( 'PF'||TO_CHAR(PROFILESEQ.NEXTVAL)
, SELECT PIN_NO
  FROM USERS
  WHERE NICKNAME='이슬이')
, 2
, 41
, SYSDATE);


--[유저 사용 언어 + 환경]===========================

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='도라에몽'))
,1);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='도라에몽'))
,11);


INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='도라에몽'))
,21);



INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='노진구'))
,2);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='노진구'))
,12);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='노진구'))
,22);



INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='비실이'))
,3);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='비실이'))
,13);


INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='비실이'))
,23);



INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='퉁퉁이'))
,4);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='퉁퉁이'))
,14);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='퉁퉁이'))
,24);


INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='이슬이'))
,5);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='이슬이'))
,15);

INSERT INTO USER_TOOL
( UTOOL_NO
, PROFILE_NO
, TOOL_NO)
VALUES
( 'UT'||'TO_CHAR(UTOOLNOSEQ.NEXTVAL)'
, (SELECT PROFILE_NO
    FROM PROFILE
    WHERE PIN_NO =(SELECT PIN_NO
                   FROM USERS
                   WHERE NICKNAME='이슬이'))
,25);


-- 모집 공고 생성==============
RECRUITNOSEQ.NEXTVAL

INSERT INTO RECRUIT
( RECRUIT_NO
, PIN_NO
, DO_TYPE_NO
, TITLE
, CONTENT
, CREATED_DATE
, PRJ_START
, PRJ_END)
VALUES
( 'RC'||RECRUITNOSEQ.NEXTVAL
, (SELECT PIN_NO
   FROM USERS
   WHERE NICKNAME='도라에몽')
, 1 
, '주차 시스템 프로젝트'
, '주차 시스템 프로젝트에 관련된 내용'
, TO_DATE('2023-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
, TO_DATE('2023-08-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
, TO_DATE('2023-09-20 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
);

-- 어느 포지션 영입할 건지
INSERT INTO RECRUIT_POS
( RECRUIT_TOOL_NO
, RECRUIT_NO
, TOOL_NO)
VALUES
( 'RP'||RECRUITPOSSEQ.NEXTVAL
, SELECT RECRUIT_NO
  FROM RECRUIT
  WHERE PIN_NO = (SELECT PIN_NO FROM USERS WHERE NIKNAME="도라에몽")
, 1);

INSERT INTO RECRUIT_POS
( RECRUIT_TOOL_NO
, RECRUIT_NO
, TOOL_NO)
VALUES
( 'RP'||RECRUITPOSSEQ.NEXTVAL
, SELECT RECRUIT_NO
  FROM RECRUIT
  WHERE PIN_NO = (SELECT PIN_NO FROM USERS WHERE NIKNAME="도라에몽")
, 2);

INSERT INTO RECRUIT_POS
( RECRUIT_TOOL_NO
, RECRUIT_NO
, TOOL_NO)
VALUES
( 'RP'||RECRUITPOSSEQ.NEXTVAL
, SELECT RECRUIT_NO
  FROM RECRUIT
  WHERE PIN_NO = (SELECT PIN_NO FROM USERS WHERE NIKNAME="도라에몽")
, 3);


-- 팀장 자동 지원 및 1차 합격까지

INSERT INTO APPLY
( APPLY_NO
, RECRUIT_POS_NO
, PIN_NO
, CONTENT
, APPLY_DATE)
VALUES
( 'AP'||TO_CHAR(APPLYNOSEQ.NEXYVAL)
, 특정 팀장의 RECRUIT_POS_NO 가 들어가는 자리
, (SELECT PIN_NO FROM USERS WHERE NICKNAME='도라에몽')
, CONTENT
, APPLY_DATE);


INSERT INTO FIRST_CK
(FIRST_CK_NN
, APPLY_NO
, PASS_DATE)
VALUES
( 'FS'||FIRSTCKSEQ.NEXEVAL
, 특정 팀장의 APPLY_NO 가 들어가는 자리
, SYSDATE);


INSERT INTO RECRUIT
( RECRUIT_NO
, PIN_NO
, DO_TYPE_NO
, TITLE
, CONTENT
, CREATED_DATE
, PRJ_START
, PRJ_END)
VALUES
( 'RC'||RECRUITNOSEQ.NEXTVAL
, (SELECT PIN_NO
   FROM USERS
   WHERE NICKNAME='노진구')
, 1 
, '메신저 시스템 프로젝트'
, '메신저 시스템 프로젝트에 관련된 내용'
, TO_DATE('2023-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
, TO_DATE('2023-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
, TO_DATE('2023-11-01 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
);


-- 팀장 자동 지원 및 1차 합격까지

INSERT INTO APPLY
( APPLY_NO
, RECRUIT_POS_NO
, PIN_NO
, CONTENT
, APPLY_DATE)
VALUES
( 'AP'||TO_CHAR(APPLYNOSEQ.NEXYVAL)
, 특정 팀장의 RECRUIT_POS_NO 가 들어가는 자리
, (SELECT PIN_NO FROM USERS WHERE NICKNAME='노진구')
, CONTENT
, APPLY_DATE);


INSERT INTO FIRST_CK
(FIRST_CK_NN
, APPLY_NO
, PASS_DATE)
VALUES
( 'FS'||FIRSTCKSEQ.NEXEVAL
, 특정 팀장의 APPLY_NO 가 들어가는 자리
, SYSDATE);


==============
-- 나머지 3인에 대한 지원서 처리
INSERT INTO APPLY
( APPLY_NO
, RECRUIT_POS_NO
, PIN_NO
, CONTENT
, APPLY_DATE)
VALUES
( 'AP'||TO_CHAR(APPLYNOSEQ.NEXYVAL)
, 도라에몽의 지원서의 특정 RECRUIT_POS_NO 가 들어가는 자리
, (SELECT PIN_NO FROM USERS WHERE NICKNAME='퉁퉁이')
, CONTENT
, APPLY_DATE);


INSERT INTO APPLY
( APPLY_NO
, RECRUIT_POS_NO
, PIN_NO
, CONTENT
, APPLY_DATE)
VALUES
( 'AP'||TO_CHAR(APPLYNOSEQ.NEXYVAL)
, 노진구의 특정 RECRUIT_POS_NO 가 들어가는 자리
, (SELECT PIN_NO FROM USERS WHERE NICKNAME='비실이')
, CONTENT
, APPLY_DATE);


INSERT INTO APPLY
( APPLY_NO
, RECRUIT_POS_NO
, PIN_NO
, CONTENT
, APPLY_DATE)
VALUES
( 'AP'||TO_CHAR(APPLYNOSEQ.NEXYVAL)
, 노진구의 특정 RECRUIT_POS_NO 가 들어가는 자리
, (SELECT PIN_NO FROM USERS WHERE NICKNAME='이슬이')
, CONTENT
, APPLY_DATE);


--== 노진구 지원서에 있는 비실이와 이슬이를 1차 합격에 올림


INSERT INTO FIRST_CK
(FIRST_CK_NN
, APPLY_NO
, PASS_DATE)
VALUES
( 'FS'||FIRSTCKSEQ.NEXEVAL
, 비실이의 노진구 모집자의 공고에 대한 APPLYNO가 들어갈 자리
, TO_DATE(2023-07-16 00:00:00));



INSERT INTO FIRST_CK
(FIRST_CK_NN
, APPLY_NO
, PASS_DATE)
VALUES
( 'FS'||FIRSTCKSEQ.NEXEVAL
, 이슬이의 노진구 모집자의 공고에 대한 APPLYNO가 들어갈 자리
, TO_DATE(2023-07-17 00:00:00));


--== 노진구 공고에 1차 합격한 노진구, 비실이, 이슬이의 최종 합류 선택하는 곳
INSERT INTO FINAL(FINAL_NO, FIRST_CK_NO, PASSDATE)
VALUES('FN'||TO_CHAR(FINALNOSEQ.NEXTVAL), 팀장 노진구의 FIRST_CK, TO_DATE(2023-07-30 12:00:00))


INSERT INTO FINAL(FINAL_NO, FIRST_CK_NO, PASSDATE)
VALUES('FN'||TO_CHAR(FINALNOSEQ.NEXTVAL),비실이의 FIRST_CK, TO_DATE(2023-07-30 12:00:00))

INSERT INTO FINAL(FINAL_NO, FIRST_CK_NO, PASSDATE)
VALUES('FN'||TO_CHAR(FINALNOSEQ.NEXTVAL),이슬이의 FIRST_CK, TO_DATE(2023-07-30 13:00:00))



--== 프로젝트 확정 번호 과정
--A
SELECT COUNT(*) AS FINAL_COUNT
FROM FINAL
WHERE FIRST_CK_NO = (SELECT FIRST_CK_NO
                     FROM FIRST_CK
           WHERE APPLY_NO = (SELECT APPLY_NO
                   FROM APPLY
                                       WHERE RECUIT_POS_NO = (SELECT RECRUIT_POS_NO)
                           FROM RECRUIT_POS
                                                              WHERE RECUIT_NO =  '확인할 공고 번호'))));
--B
SELECT COUNT(*) AS RECRUIT_TOT
FROM RECRUIT_POS
WHERE RECRUIT = '확인할 공고 번호';


--A와 B가 같으면
--확인된 공고 번호를

INSERT PROJECT
( PROJECT_NO
, RECRUIT_NO
, PRJ_DATE)
VALUES
( 'PR'||TO_CHAR(PROJECTNOSEQ.NEXTVAL)
, 확인된 공고 번호
, TO_DATE(2023-07-30 13:01:00));



